# Generated by Django 4.2.9 on 2024-01-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='name',
        ),
        migrations.AddField(
            model_name='customers',
            name='username',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
